//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgingIT.DevKit.Examples.GettingStarted.Modules.CoreModule.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BridgingIT.DevKit.Examples.GettingStarted.Modules.CoreModule.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer number cannot be empty.
        /// </summary>
        public static string Validator_CustomerNumberCannotBeEmpty {
            get {
                return ResourceManager.GetString("Validator_CustomerNumberCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer number must match format CUS-YYYY-NNNNNN (e.g., CUS-2024-000001).
        /// </summary>
        public static string Validator_CustomerNumberInvalidFormat {
            get {
                return ResourceManager.GetString("Validator_CustomerNumberInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age exceeds maximum.
        /// </summary>
        public static string Validator_DateOfBirthAgeExceedsMaximum {
            get {
                return ResourceManager.GetString("Validator_DateOfBirthAgeExceedsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth cannot be in the future.
        /// </summary>
        public static string Validator_DateOfBirthCannotBeFuture {
            get {
                return ResourceManager.GetString("Validator_DateOfBirthCannotBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth out of valid range.
        /// </summary>
        public static string Validator_DateOfBirthOutOfRange {
            get {
                return ResourceManager.GetString("Validator_DateOfBirthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string Validator_InvalidValue {
            get {
                return ResourceManager.GetString("Validator_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be empty.
        /// </summary>
        public static string Validator_MustNotBeEmpty {
            get {
                return ResourceManager.GetString("Validator_MustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both first and last name must be provided.
        /// </summary>
        public static string Validator_NameBothFirstAndLastRequired {
            get {
                return ResourceManager.GetString("Validator_NameBothFirstAndLastRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;notallowed&apos; is not permitted.
        /// </summary>
        public static string Validator_NotAllowedValue {
            get {
                return ResourceManager.GetString("Validator_NotAllowedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence must be between 100000 and 999999.
        /// </summary>
        public static string Validator_SequenceOutOfRange {
            get {
                return ResourceManager.GetString("Validator_SequenceOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year out of valid range.
        /// </summary>
        public static string Validator_YearOutOfRange {
            get {
                return ResourceManager.GetString("Validator_YearOutOfRange", resourceCulture);
            }
        }
    }
}
