//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgingIT.DevKit.Examples.GettingStarted.Modules.CoreModule.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BridgingIT.DevKit.Examples.GettingStarted.Modules.CoreModule.Application.Resource" +
                            "s", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string Validator_InvalidValue {
            get {
                return ResourceManager.GetString("Validator_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be empty.
        /// </summary>
        public static string Validator_MustNotBeEmpty {
            get {
                return ResourceManager.GetString("Validator_MustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not exceed 100 characters.
        /// </summary>
        public static string Validator_MustNotExceed100Characters {
            get {
                return ResourceManager.GetString("Validator_MustNotExceed100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not exceed 128 characters.
        /// </summary>
        public static string Validator_MustNotExceed128Characters {
            get {
                return ResourceManager.GetString("Validator_MustNotExceed128Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not exceed 20 characters.
        /// </summary>
        public static string Validator_MustNotExceed20Characters {
            get {
                return ResourceManager.GetString("Validator_MustNotExceed20Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not exceed 256 characters.
        /// </summary>
        public static string Validator_MustNotExceed256Characters {
            get {
                return ResourceManager.GetString("Validator_MustNotExceed256Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One address should be marked as primary.
        /// </summary>
        public static string Validator_OnePrimaryAddressRequired {
            get {
                return ResourceManager.GetString("Validator_OnePrimaryAddressRequired", resourceCulture);
            }
        }
    }
}
