@baseUrl = https://localhost:7144

###################################################################################
### API [GET] Customers Find one                                                  #
GET {{baseUrl}}/api/core/customers/e4f672fe-82d8-7cb3-444f-4486bf6fb163 HTTP/1.1

###################################################################################
### API [GET] Customers Find all                                                  #
GET {{baseUrl}}/api/core/customers HTTP/1.1

###################################################################################
### API [POST] Customers Create                                                   #
POST {{baseUrl}}/api/core/customers HTTP/1.1
Content-Type: application/json

{
  "firstName": "John{{$randomInt 1000 9999}}",
  "lastName": "Doe{{$randomInt 1000 9999}}",
  "email": "john.doe{{$randomInt 1000 9999}}@example.com"
}

###################################################################################
### API [PUT] Customers Update                                                   #
PUT {{baseUrl}}/api/core/customers/e4f672fe-82d8-7cb3-444f-4486bf6fb163 HTTP/1.1
Content-Type: application/json

{
  "id": "e4f672fe-82d8-7cb3-444f-4486bf6fb163",
  "firstName": "John{{$randomInt 1000 9999}}changed",
  "lastName": "Doe{{$randomInt 1000 9999}}changed"
}